object FormTableView: TFormTableView
  Left = 0
  Top = 0
  BorderStyle = bsSizeToolWin
  Caption = 'FormTableView'
  ClientHeight = 415
  ClientWidth = 393
  Color = clBtnFace
  DragKind = dkDock
  DragMode = dmAutomatic
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  PixelsPerInch = 96
  TextHeight = 13
end
