object Form3DView: TForm3DView
  Left = 0
  Top = 0
  BorderStyle = bsSizeToolWin
  Caption = 'Form3DView'
  ClientHeight = 352
  ClientWidth = 388
  Color = clBtnFace
  DragKind = dkDock
  DragMode = dmAutomatic
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  OldCreateOrder = False
  OnHide = FormHide
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 13
end
